### PR TITLE
Update 

### PR DESCRIPTION
**Pull request by jamesjpk123**
Update this with relevant info

### CODE REVIEW

**Comment by jamesjpk123** [comment]
Agh, accident! :D

**Comment by P1xt** [comment]
No worries - but as an aside, if you do the CS-WD guide first, there is literally zero reason to do the Job Ready guide, it would be redundant

**Comment by P1xt** [comment]
CS-WD > Data Science would be the path without redundancy - the WD-CS and Job Ready guides would just be busy work with a low return on your time investment if you've already done CS-WD and are getting ready to start Data Science.

**Comment by jamesjpk123** [comment]
Thanks for the advice!

**Pull request closed without merging**
